{
  try {
    final int NUM_RECORDS=1000;
    final TestData.Generator generator=new TestData.Generator(SEED,KEY_MAX,VALUE_LENGTH,KeyMode.RANDOM,ValueMode.CONSTANT,VAL);
    final MutableObjectIterator<PactRecord> source=new TestData.GeneratorIterator(generator,NUM_RECORDS);
    LOG.debug("Initializing sortmerger...");
    Sorter<PactRecord> sorter=new AsynchronousPartialSorter<PactRecord>(this.memoryManager,source,this.parentTask,this.serializer,this.comparator,32 * 1024 * 1024);
    runPartialSorter(sorter,NUM_RECORDS,0);
  }
 catch (  Exception t) {
    t.printStackTrace();
    Assert.fail("Test failed due to an uncaught exception: " + t.getMessage());
  }
}
