{
  try {
    Record record=this.generateFilledDenseRecord(58);
    record.setNull(42);
    assertTrue(record.getNumFields() == 58);
    assertTrue(record.getField(42,IntValue.class) == null);
  }
 catch (  Throwable t) {
    Assert.fail("Test failed due to an exception: " + t.getMessage());
  }
}
