{
  try {
    final int NUM_INTS=1000000;
    testSequenceOfTypes(Util.randomRecords(NUM_INTS,SerializationTestTypeFactory.INT),2047);
  }
 catch (  Exception e) {
    e.printStackTrace();
    fail("Test encountered an unexpected exception.");
  }
}
