{
  LOG.info("Attempting to fail task externally " + taskNameWithSubtask);
  if (cancelOrFailAndCancelInvokable(ExecutionState.FAILED)) {
    failureCause=cause;
    notifyObservers(ExecutionState.FAILED,cause);
  }
}
