{
  try {
    testSequenceOfTypes(new IntTypeIterator(this.rnd,NUM_INTS),2048,false);
    testSequenceOfTypes(new IntTypeIterator(this.rnd,NUM_INTS),2048,true);
  }
 catch (  Exception e) {
    e.printStackTrace();
    fail("Test encountered an unexpected exception.");
  }
}
