{
  try {
    performCheckpoint(checkpointMetaData);
  }
 catch (  CancelTaskException e) {
    throw e;
  }
catch (  Exception e) {
    throw new Exception("Error while performing a checkpoint",e);
  }
}
