{
  try {
    Task task=createTask(TestInvokableCorrect.class);
    task.failExternally(new Exception("fail externally"));
    assertEquals(ExecutionState.FAILED,task.getExecutionState());
    task.run();
    assertEquals(ExecutionState.FAILED,task.getExecutionState());
    validateUnregisterTask(task.getExecutionId());
  }
 catch (  Exception e) {
    e.printStackTrace();
    fail(e.getMessage());
  }
}
