{
  RetryOnFailure retryOnFailure=description.getAnnotation(RetryOnFailure.class);
  if (retryOnFailure != null) {
    Test test=description.getAnnotation(Test.class);
    if (test.expected() != Test.None.class) {
      throw new IllegalArgumentException("You cannot combine the RetryOnFailure " + "annotation with the Test(expected) annotation.");
    }
    statement=new RetryOnFailureStatement(retryOnFailure.times(),statement);
  }
  return statement;
}
