{
  Assert.assertEquals(JobStatus.CREATED,eg.getState());
  Exception testException=new Exception("Test exception");
  eg.suspend(testException);
  verifyCancel(1);
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
  f.set(eg,JobStatus.RUNNING);
  eg.suspend(testException);
  verifyCancel(2);
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
  f.set(eg,JobStatus.FAILING);
  eg.suspend(testException);
  verifyCancel(3);
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
  f.set(eg,JobStatus.CANCELLING);
  eg.suspend(testException);
  verifyCancel(4);
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
  f.set(eg,JobStatus.FAILED);
  eg.suspend(testException);
  verifyCancel(4);
  Assert.assertEquals(JobStatus.FAILED,eg.getState());
  f.set(eg,JobStatus.FINISHED);
  eg.suspend(testException);
  verifyCancel(4);
  Assert.assertEquals(JobStatus.FINISHED,eg.getState());
  f.set(eg,JobStatus.CANCELED);
  eg.suspend(testException);
  verifyCancel(4);
  Assert.assertEquals(JobStatus.CANCELED,eg.getState());
  f.set(eg,JobStatus.SUSPENDED);
  eg.fail(testException);
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
  eg.cancel();
  Assert.assertEquals(JobStatus.SUSPENDED,eg.getState());
}
